"""add planned_start_notified to task

Revision ID: 08ae6922edf7
Revises: df6b666d115d
Create Date: 2026-01-20 20:31:12.519394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ae6922edf7'
down_revision = 'df6b666d115d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planned_start_notified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('planned_start_notified')

    # ### end Alembic commands ###
