"""Remove people table

Revision ID: 0c8d8645a4f5
Revises: a74f7e8a9d42
Create Date: 2026-01-19 15:28:02.709489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8d8645a4f5'
down_revision = 'a74f7e8a9d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('firstname', sa.VARCHAR(length=64), nullable=True),
    sa.Column('lastname', sa.VARCHAR(length=64), nullable=True),
    sa.Column('sphere', sa.VARCHAR(length=50), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
