"""add telegram and role fields to user

Revision ID: df6b666d115d
Revises: 0c8d8645a4f5
Create Date: 2026-01-20 20:22:04.819612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df6b666d115d'
down_revision = '0c8d8645a4f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('telegram_username', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('role', sa.Enum('USER', 'ADMIN', 'TRUSTED', name='userrole'), nullable=True))
        batch_op.create_unique_constraint('uq_user_telegram_chat_id', ['telegram_chat_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_telegram_chat_id', type_='unique')
        batch_op.drop_column('role')
        batch_op.drop_column('telegram_username')
        batch_op.drop_column('telegram_chat_id')

    # ### end Alembic commands ###
